name = "whats-my-ip"
main = "src/worker.ts"
compatibility_date = "2023-12-01"
compatibility_flags = [ "nodejs_compat" ]

vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }