name = "whats-my-ip"
main = "src/worker.ts"
compatibility_date = "2023-10-25"
compatibility_flags = [ "nodejs_compat" ]

vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }