#!/usr/bin/env bun
import { writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { z } from 'zod';

const Bootstrap = z.object({
	version: z.string(),
	publication: z.string(),
	description: z.string().optional(),
	services: z.array(z.tuple([z.array(z.string()), z.array(z.string().url())]))
});

type Bootstrap = z.infer<typeof Bootstrap>;

const fetchBootstrap = async (url: string): Promise<Bootstrap> => {
	const res = await fetch(url);
	if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
	return Bootstrap.parse(await res.json());
};

const pickHttps = (urls: string[]): string => {
	const https = urls.find((u) => u.startsWith('https://'));
	if (!https) throw new Error(`No https URL in ${urls.join(', ')}`);
	return https.endsWith('/') ? https : `${https}/`;
};

const toServices = (data: Bootstrap) =>
	data.services.map(([ranges, urls]) => ({ ranges, url: pickHttps(urls) }));

const render = (v4: Bootstrap, v6: Bootstrap) => {
	const v4Services = toServices(v4);
	const v6Services = toServices(v6);
	return `// Generated by scripts/update-rdap-bootstrap.ts — do not edit by hand.
// Source: https://data.iana.org/rdap/{ipv4,ipv6}.json

export interface RdapService {
	ranges: readonly string[];
	url: string;
}

export interface RdapBootstrap {
	publication: string;
	services: readonly RdapService[];
}

export const RDAP_BOOTSTRAP_V4: RdapBootstrap = ${JSON.stringify(
		{ publication: v4.publication, services: v4Services },
		null,
		'\t'
	)};

export const RDAP_BOOTSTRAP_V6: RdapBootstrap = ${JSON.stringify(
		{ publication: v6.publication, services: v6Services },
		null,
		'\t'
	)};
`;
};

const main = async () => {
	console.log('Fetching IANA RDAP bootstrap data...');
	const [v4, v6] = await Promise.all([
		fetchBootstrap('https://data.iana.org/rdap/ipv4.json'),
		fetchBootstrap('https://data.iana.org/rdap/ipv6.json')
	]);
	console.log(`  ipv4 published ${v4.publication} (${v4.services.length} services)`);
	console.log(`  ipv6 published ${v6.publication} (${v6.services.length} services)`);

	const out = resolve(import.meta.dir, '../src/lib/server/rdap-bootstrap.ts');
	await writeFile(out, render(v4, v6));
	console.log(`Wrote ${out}`);
};

main().catch((e) => {
	console.error(e);
	process.exit(1);
});
